project:
  type: website

description-meta: "Monica Reggiani's personal website."

website:
  title: "Monica Reggiani"
  site-url: "https://monicareggiani.github.io/"
  repo-url: "https://github.com/monicareggiani/monicareggiani.github.io"
  description: "Website of Monica Reggiani"
#  favicon: /files/icon.png
  cookie-consent: true
  search: true
  navbar:
#.  background: "99ccff"
#   logo: /files/logo.png
    right:
#      - href: index.qmd
#        text: Home
      - href: colophon.qmd
        text: Colophon
#      - href: contact.qmd
#        text: Contact
  page-footer:
    left: |
      {{< fa regular copyright >}} Monica Reggiani, 2023<br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [these folks.](colophone.html)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/monicareggiani/monicareggiani.github.io)



execute:
  freeze: auto




format:
  html:
    theme: 
      light: flatly
      dark: slate
    css: customstyle.css
    toc: true

editor: visual
